### ISSUE TITLE
"KENLM lazyken=0" isn't numeric

### ISSUE THREAD

**Issue by alvations** [moses-smt/mosesdecoder#108]
It's a strange warning but when using `train-model.perl`, this occurs:

```
(9) create moses.ini @ Wed Apr 22 12:57:15 CEST 2015
Argument "KENLM lazyken=0" isn't numeric in numeric eq (==) at /home/username/moses/scripts/training/train-model.perl line 2140.
```

Although it gives the warning, the `moses.ini` is totally use-able and moses decodes with the resulting `moses.ini`. 

Why did it give such a warning? Is there something wrong?

**Comment by hieuhoang** [comment]
probably 'cos the original way of specifiying kenlm was '9'. Ignore it. If you're feeling brave, change the code

**Comment by pjwilliams** [comment]
Hi,

how recent is your version of Moses?  I fixed a warning like this back in February (commit 92a21f9d3a...) but may have missed some instances.

Phil

**Comment by alvations** [comment]
I was using the canonical RELEASE 3.0 from http://www.statmt.org/moses/RELEASE-3.0/binaries/linux-64bit/scripts/training/train-model.perl.

It's still using:

```
    if ($type =~ /^\d+$/) {
      # backwards compatibility if the type is given not as string but as a number
      $type = "SRILM" if $type == 0;
      $type = "IRSTLM" if $type == 1;
      $type = "KENLM lazyken=0" if $type == 8;
      $type = "KENLM lazyken=1" if $type == 9;
      die "Unknown numeric LM type given: $type" if $type =~ /^\d+$/;
    }
	
```

**Comment by pjwilliams** [comment]
OK, good.  It's safe to ignore the warning.  It's fixed in the master branch.

Phil

**Comment by hieuhoang** [comment]
closing
