### ISSUE TITLE
entropy-pruning mistake

### ISSUE THREAD

**Issue by tianliang0123** [moses-smt/mosesdecoder#114]
Each time when I used the entropy based pruning method in ~/mosesdecoder-RELEASE-3.0/contrib/relent-filter there will be a mistake as below, even I changed the version to 0.91, the mistake is still there:
Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl/5.14/File/Basename.pm line 341.
fileparse(): need a valid pathname at /home/tianliang/research/mosesdecoder-RELEASE-3.0/contrib/relent-filter/scripts/calcPruningScores.pl line 140

**Comment by tianliang0123** [comment]
Hi, I have solved the problem by define the $TRANSLATION_TABLE_FILE and $REORDERING_TABLE_FILE, such as:
my $REORDERING_TABLE_FILE;
my $TRANSLATION_TABLE;

**Comment by wlin12** [comment]
Hi Tian Liang,

Those variables should we automatically read from the moses.ini file you are passing as argument (lines 311 and 316 in that script). These need to be the absolute path, also if you are using a different template for moses.ini, these might not work.

Passing these manually like what you are doing is also fine.

Wang Ling

**Comment by tianliang0123** [comment]
Thank you very much Wang Ling, I defined the variables and gave a absolute path now it works fine both in version 0.91 and release 3.0. Thanks for your reply!
Tian Liang
