### ISSUE TITLE
Build fails when using both --with-mm and --max-kenlm-order

### ISSUE THREAD

**Issue by mjdenkowski** [moses-smt/mosesdecoder#117]
I'm getting a build error when using both --with-mm and --max-kenlm-order=8 ([build log](https://gist.github.com/mjdenkowski/9149a1440a26aa565072)).  However, if I first run:

    ./bjam --with-mm

then I run:

    ./bjam --with-mm --max-kenlm-order=8

everything builds fine.  Anyone familiar with the build system know what may be causing this?

**Comment by kpu** [comment]
Looks like a dependency that wasn't declared to the build system.  The dependency also seems unnecessary so I have deleted the include from IOWrapper.h.  Is it still broken?

**Comment by mjdenkowski** [comment]
Everything builds properly now.  Thanks!

On Mon, Jun 22, 2015 at 10:53 AM, Kenneth Heafield <notifications@github.com
