### ISSUE TITLE
Weirdness in tokenizer.perl for words ending in dot followed by lowercase letters

### ISSUE THREAD

**Issue by ozancaglayan** [moses-smt/mosesdecoder#118]
Hello,

I'm quite new to the field but noticed a weirdness when tokenizing french sentences using the script provided. Here's the minimum problematic case from a parallel corpora:

```
echo "Dans tes yeux calculateurs Les chiffres défilent tu ne peux pas me voir. tu ne peux pas me voir..." | tokenizer.perl -l fr

Dans tes yeux calculateurs Les chiffres défilent tu ne peux pas me voir. tu ne peux pas me voir ...
```

A simpler test:

```
echo "tu ne peux pas me voir.  blabla" | tokenizer.perl -l fr

tu ne peux pas me voir. blabla
```

So as you may noticed it doesn't tokenize the dot after the verb "voir" if the following character is a lowercase. This is the line 330 of the function `tokenize` in the script. What's the rationale behind that lowercase check? Also happens with English:

```
echo -n "I don't understand your reactions. weird." | tokenizer.perl -l en

I don &apos;t understand your reactions. weird .
```

Thank you!

**Comment by mosesadmin** [comment]
this was answered on the mailing list
   https://www.mail-archive.com/moses-support@mit.edu/msg12651.html
