### ISSUE TITLE
Compilation error in ExportInterface.cpp

### ISSUE THREAD

**Issue by plison** [moses-smt/mosesdecoder#121]
I get the following compilation error with the latest version of the code on the git repository:

moses/ExportInterface.cpp: In function ‘int run_as_server()’:
moses/ExportInterface.cpp:147:3: error: ‘MosesServer’ has not been declared
   MosesServer::Server server(params);
   ^
moses/ExportInterface.cpp:148:10: error: ‘server’ was not declared in this scope
   return server.run(); // actually: don't return. see Server::run()
          ^

**Comment by hieuhoang** [comment]
hold on for a day or so. There's some compilation issues with the recent commits

**Comment by hieuhoang** [comment]
actually, can you please git pull and recompile. Add this argument to the bjam command too:
   ./bjam ..... --no-xmlrpc-c

**Comment by plison** [comment]
I just tried it, but got the same compilation problem as before, unfortunately!

**Comment by ugermann** [comment]
What exactly is the command you are executing to compile?

On Sun, Aug 9, 2015 at 9:54 PM, Pierre Lison <notifications@github.com>
wrote:

> I just tried it, but got the same compilation problem as before,
> unfortunately!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moses-smt/mosesdecoder/issues/121#issuecomment-129239318>
> .
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by plison** [comment]
Simply ./bjam -j16 -a -q --no-xmlrpc-c
(with gcc-4.9 and boost 1.58).

**Comment by ugermann** [comment]
I just tried it with the latest commit (
13f2af7399c33f4f86d9db981857f83312ede865) and I am not able to to reproduce
the compile error with that command (using gcc-4.6). Is that the commit you
are working with? (you can check with 'git log')

- Uli

On Sun, Aug 9, 2015 at 10:04 PM, Pierre Lison <notifications@github.com>
wrote:

> Simply ./bjam -j16 -a -q --no-xmlrpc-c
> (with gcc-4.9 and boost 1.58).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moses-smt/mosesdecoder/issues/121#issuecomment-129240344>
> .
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by plison** [comment]
OK now with the very latest commit, it works, thanks!
