### ISSUE TITLE
NPLM double precision spec b0rks the build

### ISSUE THREAD

**Issue by michaelhutt** [moses-smt/mosesdecoder#123]
To get moses compiled with the NPLM from https://github.com/moses-smt/nplm, I had to edit lm/Jamfile to add <define>NPLM_DOUBLE_PRECISION=0 to the nplm.o object's definitions.

While I'm here, the commit that added NPLM_DOUBLE_PRECISION=0 to moses/LM/Jamfile (12439215d0a06e205a2c558a3e531204d1695942) was labeled 'compile NPLM objects with single precision', but actually compiles them with double precision. The NPLM headers enable double precision if NPLM_DOUBLE_PRECISION is defined at all - setting it to zero is still defining it. Not sure if this is a problem or not - both NPLM and moses are setting them to the same value by default, which makes them compatible.

@rsennrich

**Comment by rsennrich** [comment]
Hello Michael,

thanks for pointing this out. should be unborked now.

best wishes,
Rico
