### ISSUE TITLE
util/mmap.cc doesn't compile with a Linux kernel older than 2.6.38

### ISSUE THREAD

**Issue by hidetokazawa** [moses-smt/mosesdecoder#130]
Line 209 in util/mmap.cc refers the symbol MADV_HUGEPAGE, which is available only for a Linux kernel   later than 2.6.38. (Ref. http://linux.die.net/man/2/madvise) Compilation fails with older kernels. CentOS 6 still uses such kernel for example.

There is another reference to MADV_HUGEPAGE in util/mmap.cc but it is guarded by #ifdef. I think it is better to guard the above bare reference in a similar way.

**Comment by hieuhoang** [comment]
I saw this checkin by @kpu. https://github.com/moses-smt/mosesdecoder/commit/ebf31f3e8dd53c7059bb0c4e03a0920a5790ef6c

Is this to your liking?

**Comment by hieuhoang** [comment]
It sounds like it should be fixed now. I'm closing the issue if no-one objects
