### ISSUE TITLE
kbmira with meteor-1.5.jar is broken

### ISSUE THREAD

**Issue by raingo** [moses-smt/mosesdecoder#132]
OS: linux 64 bit
gcc version: 4.4.7
Moses version: latest github 384e0b06d298fe308bd39c6c567f9cf93f42e074

The following command, as part of the mert tunning,
```
/path/to/kbmira -J 200 --sctype METEOR --scconfig jar:path-to-meteor.jar --dense-init run1.dense  --ffile run1.features.dat --scfile run1.scores.dat -o mert.out > run1.mira.out 2> mert.log
```
will hang with meteor-1.5.jar at around 13 iterations, but OK with meteor-1.4.jar.

kbmira is constantly waiting on the following line:

https://github.com/moses-smt/mosesdecoder/blob/master/mert/MeteorScorer.cpp#L140

The data to run the commands can be downloaded at
```
https://www.dropbox.com/s/2z5ne8fb4gt8exk/data.tgz?dl=0
```

**Comment by mjdenkowski** [comment]
If you uncomment the TRACE_ERR line, what input line is being sent to Meteor?

**Comment by raingo** [comment]
The last three lines:
```
in: EVAL |||60 117 13 65 3 3 9 9 0 0 0 0 1 1 0 0 5 5 0 0 18 18 18
out: 0.0925925925925926 
in: EVAL |||58 117 12 65 2 2 8 8 0 0 0 0 1 1 0 0 5 5 0 0 16 16 16
```

**Comment by mjdenkowski** [comment]
I was able to run your command with Meteor 1.5.  It didn't hang but I did get an error I hadn't seen before and it exited with non-zero:
```
Could not close file 4
```
It still wrote a seemingly correct mert.out so I don't know if this would actually cause problems with mert-moses.pl.  Those input lines are also fine so I don't think the problem is with Meteor.

**Comment by raingo** [comment]
OK. I just realized the problem is that the meteor-1.5.jar I used is not the official one. I also got the error
```
Could not close file 4
```
, but the error is gone with the 3.0 release.
