### ISSUE TITLE
regtest submodule pointed at http: instead of https:

### ISSUE THREAD

**Issue by michaelhutt** [moses-smt/mosesdecoder#133]
The regtest submodule (in .gitmodules) is pointing to http://github.com/moses-smt/moses-regression-tests, which fails for me (git hangs). I'm not sure if this is a problem for everybody or just me. When I change it to https, everything works peachy.

**Comment by hieuhoang** [comment]
cheers. Changed
   https://github.com/moses-smt/mosesdecoder/commit/09bf755305c4895d20cc6cb3d1679483c168bbca
