### ISSUE TITLE
KenLM num-features other than 1 not working

### ISSUE THREAD

**Issue by michaelhutt** [moses-smt/mosesdecoder#138]
At least for KenLM, the modifications to moses/LM/Base.cpp from commit e36fb965 mangle the num-features parameter.

[Previously](https://github.com/moses-smt/mosesdecoder/commit/e36fb96557d0079e88eef4fc2f38147ff9455b0c#diff-453632d41b15855127402c12520f8482L37), it would call the parent StatefulFeatureFunction constructor with the minimum number of features (with OOV enabled, it would pass in 2, otherwise 1), which would be overridden by the call to FeatureFunction::ParseLine. Now, it calls the StatefulFeatureFunction constructor and *then* sets m_numScoreComponents to 2 or 1.

I'm assuming this is trying to add an extra feature for the OOV. Given that FeatureFunction defaults m_numScoreComponents to 1, could it be changed to:
```
if(m_enableOOVFeature) {
    this->m_numScoreComponents++;
    this->m_numTuneableComponents = this->numScoreComponents;
}
```

**Comment by michaelhutt** [comment]
Just a note: this makes the regression test 'phrase.basic-lm-oov' fail.

**Comment by cidermole** [comment]
Even if the KenLM implementation would support num-features larger than 1, which it does not -- what would you want to do with that?

**Comment by cidermole** [comment]
(To use the oov feature, set oov-feature=1 and num-feature=2, as in https://github.com/moses-smt/moses-regression-tests/blob/master/tests/phrase.basic-lm-oov/moses.ini)

**Comment by michaelhutt** [comment]
My mistake, my regression test repository was out of date!
