### ISSUE TITLE
Word alignments broken, appears to be from commit 69e5a1cc152de407513aa3889b2e665f32cb7507

### ISSUE THREAD

**Issue by mjdenkowski** [moses-smt/mosesdecoder#139]
Hi all,

Commit 69e5a1cc152de407513aa3889b2e665f32cb7507 seems to have broken outputting word alignments when Moses uses more than one phrase.  It looks like the code was refactored to replace the tangle that was word alignment printing.  We could just go back to using the (admittedly sub-optimal) old code if that's easier than debugging the new code.

Example:

```
moses -f moses.ini --print-alignment-info --report-segmentation

this
dieser |0-0| ||| 0-0

this is
Dies ist |0-1| ||| 0-0 1-1

this is a
Dies ist |0-1| ein |2-2| ||| 2-0

this is a test
Dies ist |0-1| ein |2-2| Test |3-3| ||| 3-0
```

Best,
Michael

**Comment by ugermann** [comment]
Fixed, I think. Could you please pull, compile and try again?

**Comment by mjdenkowski** [comment]
Everything appears to be working, thanks!
