### ISSUE TITLE
bjam --help option not available anymore

### ISSUE THREAD

**Issue by bricksdont** [moses-smt/mosesdecoder#143]
The "Getting started" page here:

http://www.statmt.org/moses/?n=Development.GetStarted

states:

_You see what options are available with bjam, run ./bjam --help_

But when I run bjam with the `--help` option, it just starts the build process and does not output help text. Looking at

https://github.com/moses-smt/mosesdecoder/blob/master/Jamroot

it seems that there is no `-help` option. Was it removed? Please either add the option back in or change the "GetStarted" page.

**Comment by michaelhutt** [comment]
If I run './bjam --help' I get the generic bjam help and then it exits without doing anything.

FWIW, I don't think that option ever existed in a useful form. I always reference the top bit of the Jamroot file for options.

**Comment by bricksdont** [comment]
@michaelhutt So, do you agree that either the Jamroot file or the documentation should be changed?

**Comment by michaelhutt** [comment]
Sure - I'll bet a patch would be readily accepted.

**Comment by hieuhoang** [comment]
You're right, --help doesn't say anything useful. I've deleted it from the website
