### ISSUE TITLE
No abbreviations files found in /home/zhaojinming/git_manager/theano_lstm_imdb/../share/nonbreaking_prefixes Tokenizing.. Done

### ISSUE THREAD

**Issue by JinmingZhao** [moses-smt/mosesdecoder#145]
when I study the theano lstm , I  referenced  this link (http://deeplearning.net/tutorial/lstm.html) run this script and there is a error about:No abbreviations files found in /home/zhaojinming/git_manager/theano_lstm_imdb/../share/nonbreaking_prefixes Tokenizing.. Done

I haven't learned perl and i don't  know the reason and i don't know  how to fix this.

could you tell me how to fix this problem? thank you very much

**Comment by gongshaojie12** [comment]
I have the save issue

**Comment by hieuhoang** [comment]
In Moses, that directory is in
   /scripts/share/nonbreaking_prefixes/
git clone Moses to get it and use it with theano

**Comment by alvations** [comment]
Soon, `nonbreaking_prefixes` will be available in `nltk` too =) https://github.com/nltk/nltk/pull/1282#issuecomment-184697029
