### ISSUE TITLE
Multithreading regression for IRSTLM interface?

### ISSUE THREAD

**Issue by ypeels** [moses-smt/mosesdecoder#148]
This is not a problem for me, as I am happy working around this using multi_moses.py as per #141; I am just submitting this issue for the sake of completeness.

As it currently stands, bin/moses throws an exception if you try to run it with --threads greater than 1.

In the history for [moses/LM/IRST.cpp](https://github.com/moses-smt/mosesdecoder/commits/master/moses/LM/IRST.cpp), it looks like commits 165092885c2f86a7b167b091ea8ccec2a1b159e1 and a1a1b6f2da3f258576a06e053916e1f9276f798f by @nicolabertoldi "made interface to IRSTLM threadsafe", but then the changes were ultimately reverted in commits 857ee21d5065b9b5f3a41ee12611fd1670ce376d and 54d0ab36f4a8467e6b5fdcd8cb8db4e21667f7eb by @ugermann, all in October 2015.

In particular, 54d0ab36f4a8467e6b5fdcd8cb8db4e21667f7eb removes some wrapping calls of

```
m_dict->incflag(1);
...
m_dict->incflag(0);
```

Thank you!

**Comment by hieuhoang** [comment]
I'm closing this issue as no-one seems to want to fix it.
