### ISSUE TITLE
Failed to clone the current version of moses

### ISSUE THREAD

**Issue by luoyangen** [moses-smt/mosesdecoder#149]
the error is: fatal: the remote end hung up unexpectedly.
Is it my git configuration error or project problem?

**Comment by j6k4m8** [comment]
Can you post information about your OS and environment? I just had success with this on both OSX Yosemite and Ubuntu 14.04 — sounds like a git config issue.

**Comment by hieuhoang** [comment]
no problems on my side. If there's no further issues, i'll close this soon
