### ISSUE TITLE
Missing xmlrpc-c libraries (solved)

### ISSUE THREAD

**Issue by j6k4m8** [moses-smt/mosesdecoder#150]
I've seen [a](http://permalink.gmane.org/gmane.comp.nlp.moses.user/5654) [few](http://comments.gmane.org/gmane.comp.nlp.moses.user/11218) [people](#) encountering the following when running `mosesserver`:

```
error while loading shared libraries: libxmlrpc_server_abyss++.so.7...
```

I first installed using the [binaries](http://www.statmt.org/moses/?n=Moses.Releases) from the statmt.org website and had this same issue.

**The solution is to build from source and compile with `--with-xmlrpc-c=/usr/local`**. (This is if you installed your xmlrpc to the default location, as per `apt-get` or the like.)

Hoping this helps out some other folks who had the same problem! The mailing list *does* mention this at  [this location](http://permalink.gmane.org/gmane.comp.nlp.moses.user/5654), but I had some difficulty finding it at first in the main documentation.

**Comment by j6k4m8** [comment]
@mosesadmin feel free to close this issue at your discretion — I wanted it to be posted so it was easily found via google search. I'm also happy to contribute to documentation if you direct me to the right place to edit/contribute!

**Comment by hieuhoang** [comment]
thanks, PM'ing you the right place to contribute the docs
