### ISSUE TITLE
train-model.perl: score-options --PhraseCount vs --NoPhraseCount

### ISSUE THREAD

**Issue by da-web** [moses-smt/mosesdecoder#157]
I tried to train a model with phrase count score (using moses from master) -> there seem to be an inconsistency in handling this PhraseCount score:

in train-model.perl itself on one place it is assumed to be positive "--PhraseCount" (when creating the ini file) and on another place it is assubmed to be negative "--NoPhraseCount" (when creating the scores and it tries to call "consolidate" with --NoPhraseCount, which is not supported by that command.

Can someone please check that and clear things up (for me I fixed it quick and dirty for now - but it seems that there is a change upcoming in how moses treats the default).

Thanks.

**Comment by hieuhoang** [comment]
probably better to ask the moses mailing list. Don't forget to subscribe to it before posting. You can subscribe here:
    http://mailman.mit.edu/mailman/listinfo/moses-support

**Comment by hieuhoang** [comment]
I'm gonna close this if there's you've solved the issue

**Comment by da-web** [comment]
Well I fixed it that's right - but master branch still has the bug -> Currently when you want to train a model with the phrasecount score it will not work. So it would be great if you could take a look at the train-model.perl script regarding the score-options PhraseCount argument and fix it there (or I can provide you with my fix if you want).

**Comment by hieuhoang** [comment]
i didn't write that feature and i don't use it. It's better to ask the mailing or send a pull request.

No one seems to answer questions on this issues page except me so we're thinking of not having the issues page

**Comment by da-web** [comment]
ah - i see. ;-)
Alright, I will prepare a pull request with my fix then...

**Comment by hieuhoang** [comment]
closing since I've pulled (and reverted the pull 'cos it failed the end-to-end test)

**Comment by da-web** [comment]
Can you re-open the issue (I dont have permission)? I will create a new pull request with NoPhraseCount option replaced by PhraseCount.

**Comment by hieuhoang** [comment]
just create a pull request. No need for issues
