### ISSUE TITLE
Lexical reordering scoring failed at /home/ubuntu/Moses/mosesdecoder/scripts/training/train-model.perl line 1924.

### ISSUE THREAD

**Issue by suraj1990** [moses-smt/mosesdecoder#159]
I am trying to build Moses translation model for EN-FR text translation. I have followed the steps in http://www.statmt.org/moses/?n=Development.GetStarted to install moses and steps in http://www.statmt.org/moses/?n=moses.baseline to train a baseline model. But I get a error saying bin/extract not found because of which I get a chain of successive errors. When I see the bin folder, there is a file named extractor and not extract. I have attached the log files. Please help me out
[logs1.txt](https://github.com/moses-smt/mosesdecoder/files/347065/logs1.txt)

No such file or directory while opening /home/ubuntu/Moses/mosesdecoder/working/train/model/extract.o.sorted.gz
Aborted (core dumped)
Exit code: 134
ERROR: Lexical reordering scoring failed at /home/ubuntu/Moses/mosesdecoder/scripts/training/train-model.perl line 1924.

**Comment by suraj1990** [comment]
@hieuhoang any inputs?

**Comment by hieuhoang** [comment]
please use the moses mailing list.
