### ISSUE TITLE
Please don't create new issues

### ISSUE THREAD

**Issue by hieuhoang** [moses-smt/mosesdecoder#160]
We're going to close this page soon. Please use the Moses mailing list instead moses-support@mit.edu. Don't forget to subscribe to the mailing list before you post:
   http://mailman.mit.edu/mailman/listinfo/moses-support
You can still create pull request if you have bug fixes you want to share

**Comment by alvations** [comment]
Oh, so we can create new issues?

**Comment by hieuhoang** [comment]
i'm trying it out to see what people prefer - mailing list or this forum

**Comment by nothingismagick** [comment]
I totally prefer git issue integration.
