### ISSUE TITLE
Placeholders should be separated by comma

### ISSUE THREAD

**Issue by lonevvolf** [moses-smt/mosesdecoder#188]
According to the documentation at http://www.statmt.org/moses/?n=Advanced.Hybrid#ntoc4 when passing multiple placeholders to the extract command, it looks like they should be separated by a space.  The actual code, however, expects them to be comma separated.  Most likely the documentation should be updated to reflect this.

**Comment by hieuhoang** [comment]
Hiya. Thanks for reporting this. I can't see where I should change it or make it clearer. Tell me what you think I should change and I'll get on the case.

**Comment by lonevvolf** [comment]
I would suggest adding a comment after the extract command example, simply
stating:
"When passing multiple placeholders to the extract command, separate them
with a comma (,)."

**Comment by hieuhoang** [comment]
cheers, done

**Comment by hieuhoang** [comment]
closing unless you have other issues with it
