### ISSUE TITLE
sentence-splitter

### ISSUE THREAD

**Issue by matanster** [moses-smt/mosesdecoder#193]
Hi,

Fiddling [the sentence splitting preprocessing util](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/ems/support/split-sentences.perl), we seem to get nothing really split. Probably a usage issue. Here's what we try in a UTF-8 terminal:

```
$ ./split-sentences.perl -b -l en
Sentence Splitter v3
Language: en
aaa? bbb ccc dd. ...a d. ..d.a

aaa? bbb ccc dd. ...a d. ..d.a
<P>
```

Any ideas off the top of your head?

Thanks!

**Comment by hieuhoang** [comment]
better off asking the mailing list. Hardly anyone pays attention to this forum
  http://mailman.mit.edu/mailman/listinfo/moses-support
please subscribe before you post

**Comment by hieuhoang** [comment]
closing this. Looks like no-one's responding to this forum

**Comment by matanster** [comment]
Why close, if it is essentially open?

**Comment by hieuhoang** [comment]
I'll reopen it, but don't be surprised if u get no response.

**Comment by matanster** [comment]
don't worry, I'll refer to it on the mailing list that you suggested :-)

**Comment by tomekd** [comment]
I know nothing about moses' sentence splitter but give a try for [eserix](https://github.com/emjotde/eserix). I used it from time to time.

**Comment by matanster** [comment]
Thanks @tomekd, do you know whether it is accommodates different languages, v.s. being just useful for English? we're looking for something covering a wide range of languages, not that the Moses script was necessarily perfect at that.

**Comment by tomekd** [comment]
Hi,

it supports the most popular languages: 
 * English
 * French
 * Spanish
 * German
 * Polish
 * Russian
 * Arabic 
 * Chinese
 * Croatian

Notice that it's really simple tool using SRX files.

**Comment by matanster** [comment]
Well, I guess, good to learn of SRX (Segmentation Rules eXchange) now :-) Other than reading the dry spec of it, may I assume that the implied algorithm comprises a two-pass flow, where first a break is matched by all the `break=yes` rules, and then the break may be avoided if it matches any of the `break=no` rules? any notable libraries that execute the rules or notable rule depos? I see version 2.0 of the standard is supposed to be "safer".

**Comment by hieuhoang** [comment]
looks like the mailing list got you good responses. Closing now
