### ISSUE TITLE
How to increase BLEU?

### ISSUE THREAD

**Issue by yapingzhao** [moses-smt/mosesdecoder#197]
Hi,
 My training corpus 64,000，Bleu value 8.8, I would like to ask how to increase the BLEU value? Where is the learning rate (alpha)?
I am newbie of mosedecoder.
Looking forward to your advice or answers.
Best regards,

yapingzhao

**Comment by hieuhoang** [comment]
that depends on the language pair, the data and the sentences your are translating. There is no 1 good answer. You could try collecting more data.
