### ISSUE TITLE
tokenizer.perl supported  language

### ISSUE THREAD

**Issue by dsj96** [moses-smt/mosesdecoder#234]
Hello, I want to know what language does this file, ```mosesdecoder\scripts\tokenizer\tokenizer.perl```,  support now? 
```WARNING: NO known abbreviations for language ar attempting fall-back to English version...```,
 Does this have any effect when I use it on Arabic？

**Comment by hieuhoang** [comment]
It supports theses languages: https://github.com/moses-smt/mosesdecoder/tree/master/scripts/share/nonbreaking_prefixes

tokenizer.pel will still run if your language isn't 1 of these but it will default to tokenizing the input as if it was English

**Comment by dsj96** [comment]
Thank you very much!
