### ISSUE TITLE
symal: permission denied

### ISSUE THREAD

**Issue by xuefeich** [moses-smt/mosesdecoder#235]
command train-model.perl failed due to the "../bin/symal: permission denied" and I have checked the permission of symal is 777
and sudo chmod -R 777 syaml doesn't work

**Comment by hieuhoang** [comment]
WHat happens wHen you run
   ./bin/symal
?
And what do you get when you run 
   ./bjam 
?

**Comment by xuefeich** [comment]
bjam failed due to ...failed gcc.link

**Comment by hieuhoang** [comment]
you have to successfully compile moses with bjam before running the training

**Comment by xuefeich** [comment]
Thank you, the problem is solved, I didn't notice that the compilation was not successful before
