### ISSUE TITLE
Multithreading is broken for hierarchical Moses

### ISSUE THREAD

**Issue by mjpost** [moses-smt/mosesdecoder#39]
Hierarchical multithreading appears to be broken (haven't tested with phrase-based). For the big picture, here is a plot of decoding times with Moses for a large German-English grammar (Europarl + Common Crawl) and three large LMs on a 64-core machine:

![moses 1](https://f.cloud.github.com/assets/455256/629821/6568e4cc-d175-11e2-8f83-1bf28dc3d68f.png)

The saturation point is reached pretty quickly --- around 16 threads.

Looking at the log files, I see that, with 1 thread, the maximum reported sentence-level decoding time (newstest2012) is about 6 seconds, and with 48 threads, it is _over 3,000 seconds_. Also, the logfile with large thread counts does not contain the logging output for all sentences.

I suspect there is a problem with your locking!

**Comment by hieuhoang** [comment]
Does anyone have any other insights and advise on this issue? Thinking of taking a long hard stare at it.

**Comment by pjwilliams** [comment]
What's the situation these days with tools for identifying contention and other issues in multithreaded applications?  It would be really helpful if a profiler / analyser could give us some direction.  I still suspect heap contention is a significant factor, even with tcmalloc, but I don't have solid evidence to back that up.

I would probably look for ways to improve performance generally and hope that it also pays off in better multithreaded behaviour.  I bet we could get some nice speed-ups by improving cache friendliness in a few critical places, but identifying those places could be tricky...

Phil

**Comment by hieuhoang** [comment]
ya, was thinking of doing other improvements and hope the multithreading issue would wash away in the changes. But i think whatever problem it is, it's specific on multithreading. I'll redo the tests again to make sure it's still a problem

will look at tools too

**Comment by kpu** [comment]
I'm having a conference call with Intel engineers tomorrow.  Can arrange to run Moses on a 56-core machine they own and have it profiled with their paid tools (i.e. VTune) using my ssh login.  But I'm also of the opinion that one should have reasonably optimized code first, so Moses in general has not been the focus.  

I think a concurrent non-locking growable hash table with one operation (FindOrInsert) will help.  This can be implemented with atomic integer operations and would eliminate the central FactorCollection lock entirely, as well as being useful for parallelizing lmplz.

**Comment by hieuhoang** [comment]
the factor collection lock isn't the problem. I took the lock out (see a post above) and the issue remained.

intel's help would be good

**Comment by kpu** [comment]
Looking at Nick's screenshots from above, it looks like a lot of std::locale stuff.  Find and kill all frequently called stringstream stuff.  It's shocking how slow that is.  Argument parsing, file naming, etc ok nobody cares but anything called frequently is an issue.  

See for instance
std::string Word::GetString
I'd be willing to template argument FakeOFStream so it can also be used as a string builder.

**Comment by hieuhoang** [comment]
ya, stringstream is my 1st port of call. FakeOFStream for string would be helpful. I may even use StringPiece if push comes to shove

**Comment by emjotde** [comment]
How about boost::object_pool instead of new and delete?

**Comment by hieuhoang** [comment]
we had object pools for hypos when moses 1st started. Didn't seem to help but might be worth looking at again

**Comment by emjotde** [comment]
Used it in my decoder just now, gives me a 50% speed-up.

**Comment by hieuhoang** [comment]
ah

**Comment by kpu** [comment]
boost::object_pool is crazy slow at random deletes.  Previous efforts in Moses failed because they overrode operator new and delete.  The right way for many MT cases is create a bunch of stuff then delete the pool.  And ideally the stuff is a POD, in which case use util/pool.hh.

**Comment by pjwilliams** [comment]
I can definitely believe that object pools would help.  A few years back, I tried using boost::object_pool (or some kind of Boost pool anyway) for a couple of small, high-churn object types in the chart decoder and that did help performance.  It seemed like it would be a pain / ugly to use more extensively but I think that was mainly because Boost support was optional back then and I had to put #ifdefs everywhere.

We should definitely look at reducing dynamic memory allocation in the first place, but that might require some significant refactoring to make an impact. e.g. could we reuse the decoding managers (and their data structures) for multiple sentences instead of constructing / destructing them each time?  Or could we move some of their data structures out into a longer-lived thread-specific object?

Phil

**Comment by bhaddow** [comment]
In single-threaded pb Moses (europarl, pop 5000), the biggest hog is the WordsBitmap. Lexicalised Reordering is pretty slow too. I didn't even run OSM ... Language querying is less than 5% so not much gain from optimising that.

**Comment by hieuhoang** [comment]
marcin - do you just use pools for hypos or for other object too? Do you delete the pool or delete individual hypos? I've messed around with pools in my own private decoder but the peak memory usage is crazily high when pruned hypos aren't immediately reused.

**Comment by emjotde** [comment]
Currently I use it for everything apart from the pools themsselves,. I
do not delete anything, only the pools go out of scope once a sentence
has been translated. You are right about memory usage, I now plan to
take a look at that. Kenneth said, that random deletion is expensive,
how about deletion of the most recent object that has been just been
created? If that was cheaper it could be useful for hypothesis
recombination where you just delete the last created hypothesis if it is
worse than an existing hypothesis with which it can recombine. That
might save a lot of space. 

W dniu 2015-09-24 11:11, Hieu Hoang napisał(a): 

> marcin - do you just use pools for hypos or for other object too? Do you delete the pool or delete individual hypos? I've messed around with pools in my own private decoder but the peak memory usage is crazily high when pruned hypos aren't immediately reused. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/moses-smt/mosesdecoder/issues/39#issuecomment-142863855

**Comment by kpu** [comment]
What pruned hypos?  I thought the point of priority-queue-driven search was that we didn't create them to begin with.  Though I guess you're referring to the flavor of cube pruning in which hypotheses are scored before being placed into the queue (which seems to perform better with the Kneser-Ney lower order approximation).  
In this case, the expectation is that there will be many deletes, but more news to follow (so it's not worth releasing the underlying memory, we just want to reuse it).  Given that the object size is almost certainly > sizeof(void*), we could maintain a linked list of free memory by storing a pointer in the free memory itself.  This would be transparent to the user, just an memory pool with amenable performance characteristics implementing new, single-delete, everything-delete.

**Comment by hieuhoang** [comment]
good point - with cube pruning and low cube pop limit, we don't have to stack prune. I was referring to the general case of normal pb

marcin - what's the multithreaded characteristic of your decoder? Does it flatten out after a certain number of threads?

**Comment by kpu** [comment]
> ya, stringstream is my 1st port of call. FakeOFStream for string would be helpful. 
Done.  util::StringStream.  Please convert and kill istream.

**Comment by hieuhoang** [comment]
okey dokey. ta

**Comment by hieuhoang** [comment]
I'm failing to replicate Nikolay's results with std::locale locking. I've ran ph and hiero, with compact, ondisk and probing pt. It may be my fault in not using the exact models, or it could have been an arbertation in the code/compiler/os that's now fixed.

I've also changed the majority or stringstream to util::StringStream, doesn't make any diff or is even worse. This kinda confirms the results.

Since this is the case, and std::stringstream is preferred over util::StringStream since it's standard, I'm not gonna change the code.

Multithreading issues are still present, the google profiler indicates the usual suspects of LM scoring, future cost estimation, memory alloc/deletes.
    9425   9.0%   9.0%     9425   9.0% lm::ngram::detail::GenericModel::ResumeScore
    8177   7.8%  16.8%     8177   7.8% Moses::SquareMatrix::CalcFutureScore
    5967   5.7%  22.5%     6414   6.1% tc_new
    5721   5.5%  28.0%     6087   5.8% operator delete
    5171   4.9%  32.9%    22668  21.7% Moses::LanguageModelKen::EvaluateWhenApplied
    4904   4.7%  37.6%     4904   4.7% std::count
    4125   3.9%  41.6%     4125   3.9% __nss_hosts_lookup
    3310   3.2%  44.7%     9212   8.8% Moses::LRState::CopyScores
    2699   2.6%  47.3%     2699   2.6% Moses::FVector::inner_product
    2530   2.4%  49.7%     9577   9.2% Moses::Hypothesis::RecombineCompare
    2258   2.2%  51.9%    57013  54.5% Moses::Hypothesis::EvaluateWhenApplied@48b3de
    2244   2.1%  54.0%     3210   3.1% std::_Rb_tree::_M_lower_bound
    1895   1.8%  55.8%     2058   2.0% Moses::FVector::operator+=
    1701   1.6%  57.5%     2766   2.6% __cxxabiv1::__si_class_type_info::__do_dyncast
    1590   1.5%  59.0%     6056   5.8% Moses::Hypothesis::Hypothesis
    1507   1.4%  60.4%     1507   1.4% _init@22c5c8
    1389   1.3%  61.8%    12361  11.8% lm::ngram::detail::GenericModel::FullScore
    1354   1.3%  63.1%     1914   1.8% Moses::ScoreComponentCollection::PlusEquals@5982aa
    1302   1.2%  64.3%    17581  16.8% Moses::LexicalReordering::EvaluateWhenApplied
    1222   1.2%  65.5%     1279   1.2% std::locale::locale
    1163   1.1%  66.6%    11069  10.6% lm::ngram::detail::GenericModel::ScoreExceptBackoff
    1149   1.1%  67.7%     3467   3.3% Moses::PhraseBasedReorderingState::Compare
    1122   1.1%  68.7%     7723   7.4% Moses::Hypothesis::~Hypothesis
    1099   1.1%  69.8%    87000  83.2% Moses::SearchNormal::ExpandHypothesis
    1079   1.0%  70.8%     4159   4.0% __dynamic_cast
    1044   1.0%  71.8%     2335   2.2% Moses::LRState::ComparePrevScores
     996   1.0%  72.8%     4467   4.3% Moses::BidirectionalReorderingState::Compare
     889   0.8%  73.6%      936   0.9% boost::unordered::unordered_map::~unordered_map
     861   0.8%  74.5%     1666   1.6% std::has_facet
     843   0.8%  75.3%    87885  84.0% Moses::SearchNormal::ExpandAllHypotheses

**Comment by hieuhoang** [comment]
Was a bit more careful with replacing std::stringstream with Ken's util::StringStream. Seems to speed it up by 5-8%. Added it to master.
	1	5	10	15	20	25	30	35
PB								
66	real    4m24.540s	real    1m12.628s	real    0m44.240s	real    0m38.065s	real    0m35.936s	real    0m34.983s	real    0m35.238s	0m35.903s
baseline 16/10	user    4m7.581s	user    5m16.623s	user    5m55.853s	user    7m8.261s	user    8m24.692s	user    9m35.957s	user    10m41.754s	11m14.898s
	sys     0m16.950s	sys     0m35.524s	sys     0m59.154s	sys     1m35.500s	sys     2m21.856s	sys     3m18.329s	sys     4m37.733s	4m53.832s
								
67	4m2.450s	real    1m9.583s	real    0m41.223s	real    0m35.918s	real    0m33.650s	real    0m32.582s	real    0m32.801s	0m33.056s
(66) + stringstream	3m45.788s	user    5m2.021s	user    5m24.412s	user    6m37.447s	user    7m27.481s	user    7m50.412s	user    8m46.245s	9m12.254s
	0m16.653s	sys     0m34.775s	sys     1m0.640s	sys     1m32.920s	sys     2m28.489s	sys     3m47.586s	sys     4m59.391s	5m15.233s
								
Hiero								
8	real    5m22.304s	real    1m26.084s	real    1m0.364s	real    0m56.571s	real    0m57.108s	real    0m56.578s	real    0m57.762s	1m2.664s
16/10 baseline	user    4m40.777s	user    6m5.685s	user    8m21.369s	user    11m35.756s	user    14m51.221s	user    17m17.429s	user    19m48.419s	20m15.030s
	sys     0m41.285s	sys     0m55.032s	sys     1m8.703s	sys     1m35.206s	sys     2m18.381s	sys     2m57.654s	sys     3m46.903s	5m35.132s
								
9	real    5m1.216s	real    1m20.569s	real    0m54.767s	real    0m50.152s	real    0m51.000s	real    0m52.046s	real    0m54.673s	0m59.044s
(8) + string stream	user    4m21.223s	user    5m39.820s	user    7m24.244s	user    10m1.325s	user    13m1.832s	user    15m19.240s	user    17m28.925s	18m6.981s
	sys     0m39.832s	sys     0m53.977s	sys     1m13.752s	sys     1m37.606s	sys     2m5.389s	sys     2m59.567s	sys     4m13.025s	5m2.339s

**Comment by hieuhoang** [comment]
@bhaddow Hypotheses now share bitmaps. Some improvements, especially if the pop limit is high and there's lots of threads. But still pretty mediocre (~5-10%)

**Comment by bhaddow** [comment]
Scanning bitmaps for gaps can be slow - especially at high pop limits. I think that's why Moses::SquareMatrix::CalcFutureScore is so high up the list.

**Comment by kpu** [comment]
Coverage represented as array of 64-bit integers + bit operations + bsr/bsf instruction and gcc intrinsic = hardware-implemented scanning

**Comment by hieuhoang** [comment]
CalcFutureScore() was in an inner loop but could have been moved out. about 3% gain. The profiler now looks like this as of yesterday. Memalloc is the elephant in the room
pb, perf_bitmap2
    1988  16.1%  16.1%     1988  16.1% 0x00007fff32fb57c2
     885   7.2%  23.2%     1093   8.8% tc_new
     602   4.9%  28.1%     1304  10.5% Moses::Hypothesis::~Hypothesis
     499   4.0%  32.1%      967   7.8% operator delete
     386   3.1%  35.3%      467   3.8% Moses::MonotonicVector::at
     354   2.9%  38.1%      354   2.9% lm::ngram::detail::GenericModel::ResumeScore
     351   2.8%  41.0%      468   3.8% tcmalloc::ThreadCache::ReleaseToCentralCache
     289   2.3%  43.3%     1534  12.4% Moses::PhraseDecoder::DecodeCollection
     236   1.9%  45.2%      390   3.2% std::__adjust_heap
     229   1.9%  47.1%      450   3.6% Moses::BidirectionalReorderingState::~BidirectionalReorderingState
     216   1.7%  48.8%      296   2.4% boost::unordered::unordered_set::clear
     214   1.7%  50.5%      214   1.7% std::count
     175   1.4%  52.0%      177   1.4% tcmalloc::CentralFreeList::FetchFromSpans
     172   1.4%  53.3%      181   1.5% boost::hash_value
     144   1.2%  54.5%      144   1.2% _init@233250
     129   1.0%  55.6%     1675  13.5% Moses::LexicalReorderingTableCompact::GetScore
     122   1.0%  56.5%      237   1.9% std::__push_heap
     120   1.0%  57.5%      151   1.2% boost::unordered::unordered_set::find
     117   0.9%  58.5%      184   1.5% Moses::BitmapContainerOrderer::operator
     108   0.9%  59.3%     1734  14.0% Moses::Hypothesis::EvaluateWhenApplied@4687d0
     107   0.9%  60.2%      672   5.4% Moses::LanguageModelKen::EvaluateWhenApplied
     106   0.9%  61.1%      377   3.0% Moses::LRState::CopyScores
     105   0.8%  61.9%      105   0.8% Moses::FVector::operator+=
     104   0.8%  62.7%      104   0.8% __GI___pthread_mutex_lock
     101   0.8%  63.6%      101   0.8% __lll_unlock_wake
      92   0.7%  64.3%      343   2.8% Moses::Hypothesis::Hypothesis
      84   0.7%  65.0%      160   1.3% std::_Rb_tree::_M_lower_bound
      83   0.7%  65.7%       83   0.7% Moses::FVector::inner_product
      82   0.7%  66.3%      170   1.4% Moses::HypothesisScoreOrdererWithDistortion::operator
      81   0.7%  67.0%       81   0.7% Moses::Simple9::DecodeAndSum

**Comment by nikhilkandur** [comment]
any new insight on this issue ?

**Comment by hieuhoang** [comment]
working on it. Do you use phrase-based or hiero models? What is the specs of your servers, and how many servers do you use?

**Comment by nikhilkandur** [comment]
I use phrase-based binarized models, PhraseDictionaryBinary. I use 2 servers each of them with 40 cores. The number of threads saturate at 27, to be precise; if I mention the number of threads as 40. 

i have also tried linking tc_malloc but there isn't significant difference in decoding time. But I haven't run enough to compare the statistics with and without using tc_malloc.

**Comment by nikhilkandur** [comment]
Here, I am posting the _dynamic dependencies_ (ldd) of 2 versions of mosesserver, v0.9 and v2.1 captured in the **same box**. _v0.9_ works fine with multi-threading setup without any saturation to threads allocation in contrast to _v2.1.1_. There are differences (_have marked them below_) in number of dependencies between these 2 versions (_there will be as the later version has evolved with more changes compared to previous version_). Hope this dependencies' list might help. 

#### 1. mosesserver v0.9
```sh
$ ldd mosesserver    
		linux-vdso.so.1 =>  (0x00007ffc1ce95000)
        libxmlrpc_server_abyss++.so.4 => /usr/lib64/libxmlrpc_server_abyss++.so.4 (0x00007f29f398d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00000033d2400000)
        libz.so.1 => /lib64/libz.so.1 (0x00000033d2c00000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00000033d4000000)
        libm.so.6 => /lib64/libm.so.6 (0x00000033d2000000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00000033d3800000)
        libc.so.6 => /lib64/libc.so.6 (0x00000033d1c00000)
        libxmlrpc_server++.so.4 => /usr/lib64/libxmlrpc_server++.so.4 (0x00007f29f3784000)
        libxmlrpc++.so.4 => /usr/lib64/libxmlrpc++.so.4 (0x00007f29f3572000)
        libxmlrpc_server_abyss.so.3 => /usr/lib64/libxmlrpc_server_abyss.so.3 (0x00007f29f336c000)
        libxmlrpc_abyss.so.3 => /usr/lib64/libxmlrpc_abyss.so.3 (0x00007f29f3155000)
        libxmlrpc_util.so.3 => /usr/lib64/libxmlrpc_util.so.3 (0x00000033df800000)
        libxmlrpc_server.so.3 => /usr/lib64/libxmlrpc_server.so.3 (0x00007f29f2f4e000)
        libxmlrpc.so.3 => /usr/lib64/libxmlrpc.so.3 (0x00000033df400000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00000033d7c00000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00000033d2800000)
	
        **/lib64/ld-linux-x86-64.so.2 (0x00000033d1800000)**
```
#### 2. mosesserver v2.1.1
```sh
        linux-vdso.so.1 =>  (0x00007ffdd234f000)
		libxmlrpc_server_abyss++.so.4 => /usr/lib64/libxmlrpc_server_abyss++.so.4 (0x00007ffb921e9000)
		libpthread.so.0 => /lib64/libpthread.so.0 (0x00000033d2400000)
        libz.so.1 => /lib64/libz.so.1 (0x00000033d2c00000)
		libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00000033d4000000)
		libm.so.6 => /lib64/libm.so.6 (0x00000033d2000000)
		libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00000033d3800000)
		libc.so.6 => /lib64/libc.so.6 (0x00000033d1c00000)
		libxmlrpc_server++.so.4 => /usr/lib64/libxmlrpc_server++.so.4 (0x00007ffb91fe1000)
		libxmlrpc++.so.4 => /usr/lib64/libxmlrpc++.so.4 (0x00007ffb91dcf000)
		libxmlrpc_server_abyss.so.3 => /usr/lib64/libxmlrpc_server_abyss.so.3 (0x00007ffb91bc8000)
		libxmlrpc_abyss.so.3 => /usr/lib64/libxmlrpc_abyss.so.3 (0x00007ffb919b2000)
		libxmlrpc_util.so.3 => /usr/lib64/libxmlrpc_util.so.3 (0x00000033df800000)
		libxmlrpc_server.so.3 => /usr/lib64/libxmlrpc_server.so.3 (0x00007ffb917ab000)
		libxmlrpc.so.3 => /usr/lib64/libxmlrpc.so.3 (0x00000033df400000)
        /lib64/ld-linux-x86-64.so.2 (0x00000033d1800000)
		libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00000033d7c00000)
		libdl.so.2 => /lib64/libdl.so.2 (0x00000033d2800000)
		
		**libbz2.so.1 => /lib64/libbz2.so.1 (0x00000033d8400000)**
        **libSegFault.so => /lib64/libSegFault.so (0x00007ffb923ef000)**
        **librt.so.1 => /lib64/librt.so.1 (0x00000033d3000000)**
```

**Comment by hieuhoang** [comment]
Thanks. What do you mean by thread saturation? It would be more useful if you show us decoding speed v. number threads. For whatever version you think is best, and the latest moses version from github as that's the 1 we would work with

**Comment by nikhilkandur** [comment]
**Thread saturation:**
In v2.1.1, even I set thread count, say 40 (_40 cores_ dedicated box); the number of threads in the pool varies around somewhere between 11 to 27. It never go beyond 27.

Where as v0.9, if I set thread count, **say 40**; the number of threads in the pool is consistently 40

Sorry, I am testing currently some languages on v2.1.1 and v0.9. Here are some statistics, all of the below in _seconds_ and Count is number of lines. 

I have used _PhraseDictionaryBinary_ in this experiment and I guess in v2.1.1 we don't capture statistics time for _loading translation pairs_ in memory and, through this experiment I found that is the culprit which consumes more time than Collecting Options and Search times.

**v2.1.1**
_Collecting Options time:_

| Langauge | Sum     | Count | Mean       | Median    | Min    | Max      |
|----------|---------|-------|------------|-----------|--------|----------|
| Polish   | 334.929 | 42442 | 0.007891   | 0.004287  | 0.0001 | 2.58207  |
| Russian  | 134.068   | 23786 | 0.00563643 | 0.0027103 | 0.0001 | 0.277772 |

_Search time:_

| Langauge | Sum     | Count | Mean     | Median   | Min    | Max     |
|----------|---------|-------|----------|----------|--------|---------|
| Polish   | 4222.96 | 33624 | 0.125594 | 0.044421 | 0.0001 | 3.90644 |
| Russian  | 1485.22 | 19209 | 0.077319 | 0.012238 | 0.0001 | 1.83988 |

**v0.9:**
_Translation time:_

| Langauge | Sum     | Count | Mean     | Median | Min | Max    |
|----------|---------|-------|----------|--------|-----|--------|
| Japanese | 37316   | 24129 | 1.54652  | 0.07   | 0   | 111.92 |
| Korean   | 17267.5 | 23943 | 0.721191 | 0.03   | 0   | 82.73  |

**Comment by hieuhoang** [comment]
You can try out our experimental decoder (moses2) which is 7-15 times faster then moses and doesn't suffer from speed degradation when using large number of cores. The code is in the branch perf_moses2 at the moment. 
![fr-en-speed](https://cloud.githubusercontent.com/assets/691732/15910512/184ea944-2dc3-11e6-8ba4-9e7abb43e536.png)
NOTE - It only supports a limited subset of functionality, described in the doc below
[Moses2 implemented functionality.docx](https://github.com/moses-smt/mosesdecoder/files/305683/Moses2.implemented.functionality.docx)

**Comment by hieuhoang** [comment]
I hope Moses2 and the accompaning paper goes some way towards  identifying the issues with multi-threaded decoding and fixing the problems. Took a lot of advise from this chat so thanks to everyone.

Will finally close this ticket if no-one objects
