### ISSUE TITLE
Loading table into memory...^@Exception: vector::_M_range_check

### ISSUE THREAD

**Issue by lsgrep** [moses-smt/mosesdecoder#68]
I am having this error, and  I could not find an answer from google. Could you tell me what might possibly went wrong ?
$ moses -f /tmp/shared/model/moses.ini < /tmp/shared/model/in  > /tmp/shared/model/out
Defined parameters (per moses.ini or switch):
        config: /tmp/shared/model/moses.ini
        distortion-file: 0-0 wbe-msd-bidirectional-fe-allff 6 /tmp/shared/model/reordering-table.wbe-msd-bidirectional-fe.gz
        distortion-limit: 6
        input-factors: 0
        lmodel-file: 0 0 5 /tmp/shared/ch.lm
        mapping: 0 T 0
        ttable-file: 0 0 0 5 /tmp/shared/model/phrase-table.gz
        ttable-limit: 20
        weight-d: 0.3 0.3 0.3 0.3 0.3 0.3 0.3
        weight-l: 0.5000
        weight-t: 0.2 0.2 0.2 0.2 0.2
        weight-w: -1
line=SRILM factor=0 order=5 num-features=1 path=/tmp/shared/ch.lm
FeatureFunction: SRILM0 start: 0 end: 0
line=Distortion
Feat

**Comment by bks-git** [comment]
I think you can try change "PhraseDictionaryCompact" to "PhraseDictionaryBinary"
