### ISSUE TITLE
Build failure on fedora 20

### ISSUE THREAD

**Issue by ozancaglayan** [moses-smt/mosesdecoder#89]
Hi,

There are some linking issues with system boost on Fedora Linux 20. Adding:
```
<library>boost_filesystem
```
to `Jamroot` fixes the issue.

**Comment by hieuhoang** [comment]
I built boost (v1.57) myself and linked moses to it. It works ok
   ./bjam --with-boost=/home/hieu/workspace/boost_1_57_0 --with-irstlm=/home/hieu/workspace/irstlm-5.80.06/trunk --with-cmph=/home/hieu/workspace/cmph-2.0 -j2 
I always recommend building boost yourself as some versions are buggy and the linux distros don't always keep up with the updates. Also, moses (and all other programs that need boost) are sensitive exactly how the library files are named so you need to control it yourself

The instructions to build boost to work with moses is here
   http://www.statmt.org/moses/?n=Development.GetStarted
