### ISSUE TITLE
Bug in your mosesdecoder/phrase-extract/SyntaxTree.cpp

### ISSUE THREAD

**Issue by RyanLiu1900** [moses-smt/mosesdecoder#91]
Hi, this code has some bug, may it get the syntax structure wrong.
For example, use this SyntaxTree, I build this syntax tree.

  SyntaxTree st;
  st.AddNode(0, 2, "X2"); // add a node cover 0 and 2
  st.AddNode(0, 3, "X3");
  st.AddNode(1, 2, "X1");
  st.ConnectNodes();

But after it construct the tree, I find that the parent of "X1" is "X3" !!

**Comment by pjwilliams** [comment]
Hi,

the ConnectNodes function requires that the SyntaxTree's nodes describe a complete tree (i.e. it doesn't assume that there is an implicit node for each word of the associated sentence or anything like that).  If you add a couple of extra nodes to cover the gaps then it should work as expected:

SyntaxTree st;
st.AddNode(0, 2, "X2"); // add a node cover 0 and 2
st.AddNode(0, 3, "X3");
st.AddNode(1, 2, "X1");
st.AddNode(0, 0, "Y");
st.AddNode(3, 3, "Z");
st.ConnectNodes();

Please let me know if it doesn't...

Phil

**Comment by RyanLiu1900** [comment]
Got it! Thanks very much.
