### ISSUE TITLE
No file "processPhraseTable" in "mosesdecoder/bin"

### ISSUE THREAD

**Issue by LittleNoah** [moses-smt/mosesdecoder#92]
I was doing the manual's baseline system chapter. And after training the translation model, I want to binarise the phrase-table but it seems no file named "processPhraseTable" in "mosesdecoder/bin". Does this version remove it ? Yesterday I clone moses from github. And my system is openSUSE 13.2, using boost1.54.
The building process is successful.

**Comment by hieuhoang** [comment]
Yes, the processPhraseTable has been removed and the manual's baseline system chapter has been updated. This email to the moses mailing list tell you why
   https://www.mail-archive.com/moses-support@mit.edu/msg11367.html
I recommend compiling moses with cmph then binarizing with
   processPhraseTableMin
It's small and fast

**Comment by LittleNoah** [comment]
I'm sorry. But How do I use "processPhraseTableMin"? I don't find it in 'bin'...

**Comment by hieuhoang** [comment]
recompile with the cmph library. This link tells you how
 http://www.statmt.org/moses/?n=Moses.AdvancedFeatures#ntoc12

**Comment by LittleNoah** [comment]
Thank you. I think it is the key for me.

**Comment by Oduola** [comment]
I've been having problem compiling moses with cmph,I had it compiled before but when i ran into problem during the testSet and bleu score process, i decided to recompile with cmph.
 i used 2 different command but both ended in the same error message : ./bjam -a --static -j`nproc` --with-mm --with-cmph=$WORK/cmph-2.0/build and  ./bjam --with-cmph=/Users/hieu/workspace/cmph-2.0

*** No errors detected
...failed updating 2 targets...
...skipped 87 targets...
...updated 905 targets...
The build failed.  If you need support, run:
  /usr/bin/bjam -a --static -j4 --with-mm --with-cmph=/home/taye/cmph-2.0/build --debug-configuration -d2 |gzip >build.log.gz
then attach build.log.gz to your e-mail.
You MUST do 3 things before sending to the mailing list:
   1. Subscribe to the mailing list at http://mailman.mit.edu/mailman/listinfo/moses-support
   2. Attach build.log.gz to your e-mail
   3. Say what is the EXACT command you executed when you got the error
ERROR

**Comment by hieuhoang** [comment]
send your question to the Moses mailing list. Include the build.log.gz

Don't forget to subscribe to the mailing list 1st. You can subscribe here:
   http://mailman.mit.edu/mailman/listinfo/moses-support
