### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by mjpost** [moses-smt/mosesdecoder#97]
There are no build instructions in the [BUILD-INSTRUCTIONS.txt file](https://github.com/moses-smt/mosesdecoder/blob/RELEASE-3.0/BUILD-INSTRUCTIONS.txt) in the 3.0 release (it seems a placeholder crept through). The [getting started guide](http://www.statmt.org/moses/?n=Development.GetStarted) refers to these.

**Comment by hieuhoang** [comment]
oh, changed the webpage. All instructions are on the website these days
